### ISSUE TITLE
Ps3 says corrupted

### ISSUE THREAD

**Issue by redrush25** [Tonic-Box/D3Studio#11]
After modding the save file with your editor no matter what I change, when I put it back into ps3 for export it says data corrupted and I end up losing characters etc before I can I export.
It doesn't do this with devilson's editor.

**Comment by Tonic-Box** [comment]
First, I dev'd devils editors, or rather last like 4 renditions of it (peek the credits/mentions in the editor for gsec or tonicbox). Second, you're probably putting like too many sockets or something on the item. Hard to help unless you post pics etc of what exactly you're trying to do. eg item stats, etc.
