### ISSUE TITLE
Ethereal affix?

### ISSUE THREAD

**Issue by CheeseArmpits** [Tonic-Box/D3Studio#12]
Hello, not really an issue, but it's a method of reaching you, my apologies.
First, I'd like to say thank you for the programs and the guides, they have been very good at revitalizing my interest in the game. I found you through the gbatemp thread, and yours was miles above the ones there.
Now I'd just like to inquire if you're still planning to update this? I mainly ask because I'm wondering if it's possible in the upcoming patch to finally add certain legendary powers to items, making for some pretty interesting d3 builds. It's mainly from the Ethereal weapons, a season-exclusive thing that comes with random legendary powers that I would presume would then be selectable as affixes. The potential being that you could stuff many legendary powers into one item like any other affix. But I'm not the expert, so I'm just reaching out and hope you read. Thank you then for reading.
Please keep up the good work, and have a good day!

**Comment by Tonic-Box** [comment]
Im not activly updating this any more more, sorry!
