### ISSUE TITLE
Ethereal Affix Code

### ISSUE THREAD

**Issue by ICheckpointI** [Tonic-Box/D3Studio#13]
you have the GBID to share with us ??

the ethereal GBID affixes i mean.. 

and thanks for the great software..

**Comment by Tonic-Box** [comment]
No sorry, i dont currently maintain or upkeep this source as i dont play anymore.

**Comment by IdontKnowtoMod** [comment]
Dear ICheckpointI  

this Editor dont offer something special, only some visuals from PC exclusive version of the game.

Dont waist your time to text to the creator.

All modding guides dont work on real life and missing to much information, for ex 0 to all is whatever suggestions......

Now for the creator, I understand you cant find the Ethereal GBID list code, and you reply (I dont play anymore....)

**Comment by Tonic-Box** [comment]
> 

1. I have not played in over a year. Been back to Runescape and client development.
2. It was with my tools that Jester and Jimmy where able to pull the ethereal affexes.
3. Weird flex
