### ISSUE TITLE
Theme?

### ISSUE THREAD

**Issue by JavaKavari01** [Tonic-Box/D3Studio#2]
Not saying that what you have as a wallpaper for D3Studio is bad, its really not but the ability to change your own wallpaper would be a cool feature. If it's not hard to do that is. Side comment I think I can speak for everyone that uses this software and say thanks for the hard work and effort you put into creating this. ;)

**Comment by Tonic-Box** [comment]
I may add something like this in. The main reason I haven't so far though is because Ive tried to keep the project as bloat-free and light weight as possible.

**Comment by dekonnnt** [comment]
> I may add something like this in. The main reason I haven't so far though is because Ive tried to keep the project as bloat-free and light weight as possible.

It makes perfect sense! The lighter and more fluid the better it is.
