### ISSUE TITLE
Editing attribute percentage

### ISSUE THREAD

**Issue by dekonnnt** [Tonic-Box/D3Studio#3]
Ask me a question! Are the values ​​that I can place on an item already defined? Ex: I want to put a percentage of damage on the item, but the editor only accepts between 13% ~ 15%. Couldn't I put it above that?

**Comment by Tonic-Box** [comment]
No you couldnt. The affixes are static. They are built into the game, and to refference them, the game saves use a DJB hash (base 0) of the affex string name. Same as weith items. These hashes are called GBIDs (Game-Balance ID)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dekonnnt** [comment]
Ohh I understand! Well, anyway congratulations on the wonderful work, it is extremely useful. Keep it up, always doing your best.

**Comment by Tonic-Box** [comment]
Much appreciated! Thanks ^-^
