### ISSUE TITLE
Magic Find

### ISSUE THREAD

**Issue by Betrezem** [Tonic-Box/D3Studio#4]
Hello! Can you tell me - I know that on the test server of the PC version there is a buff - +2000% to magic find. Tell me - is it possible to achieve the same with the help of your editor? I didn't find magic find in the character stats lists ((

**Comment by dekonnnt** [comment]
So, I never found a simple option to leave it that way. What I found is that you make an item and go putting the attributes you want several times. Of this model there:

![Screenshot_1](https://user-images.githubusercontent.com/80002270/110964315-d380c580-8331-11eb-825f-d11daf224c1d.jpg)

**Comment by Betrezem** [comment]
By the way-I'm trying to create an item with 8 such affixes. However, this does not work out for me - as a result, I only get 1 bonus in the game, not 8

**Comment by Tonic-Box** [comment]
You cant create an item with 8 affixes. you have your 6 base affixes and your mystic roll and your 7th.

The old mystic roll needs to be set but can be anything, this just signifies what the affix used to be, and new mystic roll signifies what its been rolled too.

As for the +2000% to magic find, what you see is what you get with the affixes. The affixes are not shipped with the game patches so its rather difficult to gather them, and impossible to gather ones that only show on pc as pc saves are server side and we cant access those.

So, what you see is what you get pretty much as far as the affixes goes, and this is pretty much the same with any of the editors out there.
