### ISSUE TITLE
Release all difficulties?

### ISSUE THREAD

**Issue by dekonnnt** [Tonic-Box/D3Studio#5]
Excuse me again for kind of silly questions. But and since I still don't know how to use 100% of the editor, I always had a doubt. So, I was wondering if in the editor I can release all the difficulties, I mean even the T16?

**Comment by Tonic-Box** [comment]
Yes. Go to the account general tab and set your account flag to 1012.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dekonnnt** [comment]
Thx!!!

**Comment by Tonic-Box** [comment]
Though the character must still be lvl 70 for it to access T16

Sent from ProtonMail mobile

-------- Original Message --------
