### ISSUE TITLE
I broke my monk

### ISSUE THREAD

**Issue by gx-xk** [Tonic-Box/D3Studio#7]
Not sure how yet, ill do some more digging. I have everything I brought in, the files are not corrupt, when I try to talk to Urshi, Kadala, ANYONE with a menu, it opens and then closes immediately. Checked other characters and they are all just fine. I did no work in the RAW tab, so lets rule that out now. Im going to revert back and just use my presave, however I wanted to let yall know something happened. This may happen a lot, I do things a lot, I break things, a lot. Let me know if theres anything I can do to help with this issue from my end.

**Comment by Tonic-Box** [comment]
you have negative regen set, the constant ticking of health from negative regen stat is what does this.

**Comment by Tonic-Box** [comment]
Throw some deaths bargen's on the monk or cube it, it will fix the issue for you if you'd like to keep the negative regen.

**Comment by gx-xk** [comment]
I knew I was forgetting something, its been a while. Last editor I used was CKYs so please forgive me if I post often. When I used his I was quite literally playing on the ps3 and then 4 with him and a few other guys, let me know if theres anything I can do to help out. Thanks for the help!
