### ISSUE TITLE
This is a new one for me,

### ISSUE THREAD

**Issue by gx-xk** [Tonic-Box/D3Studio#8]
I'm 100% lost as to what I did. I have a healthy backup so that's not the problem. Currently I can log in on d3 ps3, export my save fine. I pull the save from the system or the cloud, either one. I decrypt edit just 1 thing at this point. Recrypt, upload, load to the start screen where it says I've got a corrupt save and all hero's are wiped. The seen this?

**Comment by Tonic-Box** [comment]
Means you did something wring when modding your save like have more than 3 sockets on an item or something like that.

Sent from ProtonMail mobile

-------- Original Message --------
